name: Release new board revision
on:
  push:
    tags:
      - 'board-*'

jobs:
  release:
    runs-on: ubuntu-latest
    container: ghcr.io/inti-cmnb/kicad9_auto_full:latest

    steps:
      - uses: actions/checkout@v4
      - name: Build board using KiBot
        run: kibot -e "OM-64DO.kicad_sch"
        working_directory: ./kicad
      - name: Rename artifact
        run: |
          ARTIFACT_NAME="${{ github.ref_name | replace('board-', '') }}.zip"
          mv ./kicad/Release/board_artifact.zip "./kicad/Release/${ARTIFACT_NAME}"
          echo "ARTIFACT_NAME=${ARTIFACT_NAME}" >> $GITHUB_ENV
      - name: Create GitHub Release and upload board artifact
        uses: softprops/action-gh-release@v2.5.0
        with:
          files: ./kicad/Release/${{ env.ARTIFACT_NAME }}
          name: Board revision ${{ env.ARTIFACT_NAME }}
          generate_release_notes: true
          make_latest: true